// Capital cities, keyed by the exact world-atlas dataset name (same keys as
// countries.js / flags.js). A plain string means the name is identical in
// English and French; an array is [english, french].
//
// Editorial choices for the countries with several or contested capitals are
// listed at the bottom of this file.

import { getLang } from './i18n.js';

const CAPITALS = {
  'United States of America': ['Washington, D.C.', 'Washington'],
  'Canada': 'Ottawa',
  'Mexico': ['Mexico City', 'Mexico'],
  'Brazil': ['Brasília', 'Brasilia'],
  'Argentina': 'Buenos Aires',
  'Russia': ['Moscow', 'Moscou'],
  'China': ['Beijing', 'Pékin'],
  'India': 'New Delhi',
  'Australia': 'Canberra',
  'New Zealand': 'Wellington',
  'Egypt': ['Cairo', 'Le Caire'],
  'South Africa': ['Pretoria', 'Pretoria'],
  'France': 'Paris',
  'Germany': ['Berlin', 'Berlin'],
  'Spain': 'Madrid',
  'Italy': 'Rome',
  'United Kingdom': ['London', 'Londres'],
  'Japan': ['Tokyo', 'Tokyo'],
  'Turkey': 'Ankara',
  'Saudi Arabia': ['Riyadh', 'Riyad'],
  'Indonesia': 'Jakarta',
  'Portugal': ['Lisbon', 'Lisbonne'],
  'Ireland': 'Dublin',
  'Iceland': ['Reykjavík', 'Reykjavik'],
  'Norway': 'Oslo',
  'Sweden': 'Stockholm',
  'Finland': 'Helsinki',
  'Denmark': ['Copenhagen', 'Copenhague'],
  'Netherlands': 'Amsterdam',
  'Belgium': ['Brussels', 'Bruxelles'],
  'Luxembourg': 'Luxembourg',
  'Switzerland': ['Bern', 'Berne'],
  'Austria': ['Vienna', 'Vienne'],
  'Malta': ['Valletta', 'La Valette'],
  'Poland': ['Warsaw', 'Varsovie'],
  'Czechia': 'Prague',
  'Slovakia': 'Bratislava',
  'Hungary': 'Budapest',
  'Slovenia': 'Ljubljana',
  'Croatia': 'Zagreb',
  'Bosnia and Herz.': 'Sarajevo',
  'Serbia': 'Belgrade',
  'Montenegro': 'Podgorica',
  'Macedonia': 'Skopje',
  'Albania': 'Tirana',
  'Kosovo': ['Pristina', 'Pristina'],
  'Greece': ['Athens', 'Athènes'],
  'Bulgaria': 'Sofia',
  'Romania': ['Bucharest', 'Bucarest'],
  'Moldova': ['Chișinău', 'Chisinau'],
  'Ukraine': ['Kyiv', 'Kiev'],
  'Belarus': 'Minsk',
  'Lithuania': 'Vilnius',
  'Latvia': 'Riga',
  'Estonia': 'Tallinn',
  'Cyprus': ['Nicosia', 'Nicosie'],
  'Colombia': ['Bogotá', 'Bogota'],
  'Venezuela': 'Caracas',
  'Guyana': 'Georgetown',
  'Suriname': 'Paramaribo',
  'Ecuador': 'Quito',
  'Peru': 'Lima',
  'Bolivia': 'Sucre',
  'Chile': 'Santiago',
  'Paraguay': ['Asunción', 'Asuncion'],
  'Uruguay': 'Montevideo',
  'Cuba': ['Havana', 'La Havane'],
  'Haiti': 'Port-au-Prince',
  'Dominican Rep.': ['Santo Domingo', 'Saint-Domingue'],
  'Jamaica': 'Kingston',
  'Bahamas': 'Nassau',
  'Trinidad and Tobago': ['Port of Spain', "Port-d'Espagne"],
  'Belize': 'Belmopan',
  'Guatemala': ['Guatemala City', 'Guatemala'],
  'Honduras': 'Tegucigalpa',
  'El Salvador': 'San Salvador',
  'Nicaragua': 'Managua',
  'Costa Rica': 'San José',
  'Panama': ['Panama City', 'Panama'],
  'Mongolia': ['Ulaanbaatar', 'Oulan-Bator'],
  'North Korea': 'Pyongyang',
  'South Korea': ['Seoul', 'Séoul'],
  'Taiwan': 'Taipei',
  'Philippines': ['Manila', 'Manille'],
  'Vietnam': ['Hanoi', 'Hanoï'],
  'Laos': 'Vientiane',
  'Cambodia': 'Phnom Penh',
  'Thailand': 'Bangkok',
  'Myanmar': 'Naypyidaw',
  'Malaysia': 'Kuala Lumpur',
  'Singapore': ['Singapore', 'Singapour'],
  'Brunei': 'Bandar Seri Begawan',
  'Timor-Leste': 'Dili',
  'Papua New Guinea': 'Port Moresby',
  'Bangladesh': 'Dhaka',
  'Sri Lanka': 'Colombo',
  'Nepal': ['Kathmandu', 'Katmandou'],
  'Bhutan': 'Thimphu',
  'Pakistan': 'Islamabad',
  'Iran': ['Tehran', 'Téhéran'],
  'Iraq': ['Baghdad', 'Bagdad'],
  'Syria': ['Damascus', 'Damas'],
  'Lebanon': ['Beirut', 'Beyrouth'],
  'Israel': ['Jerusalem', 'Jérusalem'],
  'Palestine': 'Ramallah',
  'Jordan': 'Amman',
  'Yemen': 'Sanaa',
  'Oman': ['Muscat', 'Mascate'],
  'United Arab Emirates': ['Abu Dhabi', 'Abou Dabi'],
  'Qatar': 'Doha',
  'Bahrain': 'Manama',
  'Kuwait': ['Kuwait City', 'Koweït'],
  'Georgia': ['Tbilisi', 'Tbilissi'],
  'Armenia': ['Yerevan', 'Erevan'],
  'Azerbaijan': ['Baku', 'Bakou'],
  'Kazakhstan': 'Astana',
  'Uzbekistan': ['Tashkent', 'Tachkent'],
  'Turkmenistan': ['Ashgabat', 'Achgabat'],
  'Kyrgyzstan': ['Bishkek', 'Bichkek'],
  'Tajikistan': ['Dushanbe', 'Douchanbé'],
  'Afghanistan': ['Kabul', 'Kaboul'],
  'Morocco': 'Rabat',
  'Algeria': ['Algiers', 'Alger'],
  'Tunisia': 'Tunis',
  'Libya': 'Tripoli',
  'Ethiopia': ['Addis Ababa', 'Addis-Abeba'],
  'Kenya': 'Nairobi',
  'Nigeria': 'Abuja',
  'Madagascar': 'Antananarivo',
  'Mali': 'Bamako',
  'Niger': 'Niamey',
  'Chad': ["N'Djamena", "N'Djaména"],
  'Sudan': 'Khartoum',
  'Somalia': ['Mogadishu', 'Mogadiscio'],
  'Tanzania': 'Dodoma',
  'Mozambique': 'Maputo',
  'Angola': 'Luanda',
  'Namibia': 'Windhoek',
  'Botswana': 'Gaborone',
  'Zimbabwe': 'Harare',
  'Zambia': 'Lusaka',
  'Ghana': 'Accra',
  'Senegal': 'Dakar',
  'Cameroon': 'Yaoundé',
  'Dem. Rep. Congo': 'Kinshasa',
  'Benin': 'Porto-Novo',
  'Togo': 'Lomé',
  'Burkina Faso': 'Ouagadougou',
  "Côte d'Ivoire": 'Yamoussoukro',
  'Guinea': 'Conakry',
  'Sierra Leone': 'Freetown',
  'Liberia': 'Monrovia',
  'Mauritania': 'Nouakchott',
  'Gabon': 'Libreville',
  'Congo': 'Brazzaville',
  'Central African Rep.': 'Bangui',
  'S. Sudan': 'Juba',
  'Eritrea': 'Asmara',
  'Djibouti': 'Djibouti',
  'Uganda': 'Kampala',
  'Rwanda': 'Kigali',
  'Burundi': 'Gitega',
  'Malawi': 'Lilongwe',
  'Lesotho': 'Maseru',
  'eSwatini': 'Mbabane',
  'Eq. Guinea': 'Malabo',
  'Guinea-Bissau': 'Bissau',
  'Gambia': 'Banjul',
  'Andorra': ['Andorra la Vella', 'Andorre-la-Vieille'],
  'Liechtenstein': 'Vaduz',
  'Monaco': 'Monaco',
  'San Marino': ['San Marino', 'Saint-Marin'],
  'Vatican': ['Vatican City', 'Cité du Vatican'],
  'Comoros': 'Moroni',
  'Cabo Verde': 'Praia',
  'São Tomé and Principe': 'São Tomé',
  'Seychelles': 'Victoria',
  'Mauritius': 'Port Louis',
  'Maldives': 'Malé',
  'Solomon Is.': 'Honiara',
  'Vanuatu': 'Port-Vila',
  'Fiji': 'Suva',
  'Samoa': 'Apia',
  'Tonga': "Nuku'alofa",
  'Kiribati': 'Tarawa',
  'Micronesia': 'Palikir',
  'Marshall Is.': 'Majuro',
  'Palau': 'Ngerulmud',
  'Nauru': 'Yaren',
  'Tuvalu': 'Funafuti',
  'St. Kitts and Nevis': 'Basseterre',
  'Antigua and Barb.': "Saint John's",
  'Dominica': 'Roseau',
  'Saint Lucia': 'Castries',
  'St. Vin. and Gren.': 'Kingstown',
  'Grenada': "Saint George's",
  'Barbados': 'Bridgetown',
};

// Countries whose capital is (nearly) the country's own name: the capital is
// then a giveaway rather than a real hint. Kept playable — they are easy
// countries anyway — but listed here so the choice is explicit.
export const TRIVIAL_CAPITALS = new Set([
  'Monaco', 'Singapore', 'Vatican', 'Luxembourg', 'Djibouti', 'Panama',
  'Guatemala', 'Kuwait', 'Andorra', 'San Marino', 'Mexico', 'Brazil',
]);

// Editorial choices (several official seats, or a contested status):
//   South Africa   -> Pretoria (executive; Cape Town and Bloemfontein are the
//                     legislative and judicial seats)
//   Bolivia        -> Sucre (constitutional; La Paz is the seat of government)
//   Netherlands    -> Amsterdam (constitutional; The Hague is the seat of
//                     government)
//   Côte d'Ivoire  -> Yamoussoukro (official; Abidjan is the largest city and
//                     economic capital)
//   Tanzania       -> Dodoma (official since 1996; Dar es Salaam is the
//                     largest city)
//   Benin          -> Porto-Novo (official; Cotonou is the seat of government)
//   eSwatini       -> Mbabane (administrative; Lobamba is the legislative and
//                     royal seat)
//   Sri Lanka      -> Colombo (executive and commercial; Sri Jayawardenepura
//                     Kotte is the official legislative capital)
//   Israel         -> Jerusalem (seat of government; status disputed
//                     internationally)
//   Palestine      -> Ramallah (de facto administrative seat)
//   Nauru          -> Yaren (de facto; the country has no official capital)
//   Kiribati       -> Tarawa (South Tarawa)

export function capitalOf(name) {
  const c = CAPITALS[name];
  if (!c) return null;
  if (typeof c === 'string') return c;
  return getLang() === 'fr' ? c[1] : c[0];
}

export { CAPITALS };
